export const PLANS = [
  {
    id: "basic",
    title: "Basic",
    priceText: "0 CHF",
    periodText: "/Jahr",
    accent: "green",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Basic wählen",
    features: [
      { text: "Bis 3 aktive Kurse" },
      { text: "15% Komm. (inkl. Stripe)" },
      { text: "Standard Listing" },
      { text: "Link auf eigene Website" },
    ],
  },
  {
    id: "pro",
    title: "Pro",
    priceText: "290 CHF",
    periodText: "/Jahr",
    accent: "blue",
    badgeText: "BELIEBT",
    lift: true,
    buttonVariant: "solid",
    ctaLabel: "Pro wählen",
    features: [
      { text: "Bis 10 aktive Kurse" },
      { text: "12% Komm. bei Buchung" },
      { text: "Besseres Ranking" },
      { text: "Kontaktformular" },
      { text: "Attraktivere Darstellung" },
    ],
  },
  {
    id: "premium",
    title: "Premium",
    priceText: "590 CHF",
    periodText: "/Jahr",
    accent: "purple",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Premium wählen",
    features: [
      { text: "Bis 30 aktive Kurse" },
      { text: "10% Komm. bei Buchung" },
      { text: "Top Ranking", isStrong: true },
      { text: 'Badge "Empfohlen"' },
      { text: "Newsletter Präsenz" },
      { text: "Reporting Dashboard" },
    ],
  },
  {
    id: "enterprise",
    title: "Enterprise",
    priceText: "ab 1'190 CHF",
    periodText: "/Jahr",
    accent: "orange",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Kontaktieren",
    features: [
      { text: "Unbegrenzte Kurse", isStrong: true },
      { text: "8% Komm. bei Buchung" },
      { text: "Beste Platzierung" },
      { text: "Eigene Landingpage" },
      { text: "Personal Account Mgr." },
    ],
  },
];