export const PLANS = [
  {
    id: "basic",
    title: "Basic",
    tagline: "Kostenloser Einstieg",
    priceText: "0 CHF",
    periodText: "/Jahr",
    accent: "green",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Basic wählen",
    savingsNote: null,

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 0,
    maxCourses: Infinity,
    maxPrioCourses: 0,
    maxCategoriesPerCourse: 1,
    commissionPct: 15,
    planFactor: 1.0,
    includedCaptureServices: 0,
    bookingFactorWithKursNavi: 1.3,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "Keine Prio-Kurse", dim: true, excluded: true, description: "Prio-Kurse werden in Suche und Kategorien weiter oben angezeigt als Standard-Kurse. Diese Funktion ist ab dem Pro-Paket verfügbar." },
      { text: "1 Kategorie pro Kurs", separator: true, description: "Jeder Kurs erscheint in genau einer Kategorie. Mit einem Upgrade können Sie bis zu 3 oder 5 Kategorien pro Kurs wählen – und so mehr Interessenten erreichen." },
      { text: "15% Provision bei Direktbuchung", description: "Gilt nur, wenn Direktbuchung für den Kurs aktiviert ist. Anfragen bleiben immer provisionsfrei." },
      { text: "Ranking-Bonus bei aktivierter Direktbuchung", isStrong: true, description: "Kurse mit aktivierter Direktbuchung werden in der Suche höher gerankt als Kurse ohne Direktbuchung." },
      { text: "Standard Listing", separator: true },
      { text: "Keine Erfassungsservices inklusive", dim: true, excluded: true, description: "Separat buchbar ab 75 CHF pro Kurs." },
      { text: "Basic Analytics", description: "Einfache Statistiken zu Aufrufen und Anfragen." },
    ],
  },
  {
    id: "pro",
    title: "Pro",
    tagline: "Für wachsende Anbieter",
    priceText: "290 CHF",
    periodText: "/Jahr",
    accent: "blue",
    badgeText: "BELIEBT",
    lift: true,
    buttonVariant: "solid",
    ctaLabel: "Pro wählen",
    savingsNote: "3% weniger Kommission als Basic",

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 290,
    maxCourses: Infinity,
    maxPrioCourses: 5,
    maxCategoriesPerCourse: 3,
    commissionPct: 12,
    planFactor: 1.2,
    includedCaptureServices: 0,
    bookingFactorWithKursNavi: 1.2,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "5 Prio-Kurse", isStrong: true, description: "Sie wählen 5 Kurse als Prio-Kurse. Diese werden in Suche und Kategorieseiten prominent ganz oben angezeigt – noch vor Kursen ohne Priorisierung." },
      { text: "Erhöhtes Ranking für Prio-Kurse", isStrong: true, description: "Prio-Kurse erscheinen in allen relevanten Suchen und Kategorieübersichten weiter oben." },
      { text: "Bis 3 Kategorien pro Kurs", separator: true, description: "Pro Kurs können Sie bis zu 3 Kategorien wählen. So erscheint derselbe Kurs z.B. unter «Sport», «Fitness» und «Gesundheit» – und wird von deutlich mehr Interessenten gefunden." },
      { text: "12% Provision bei Direktbuchung", description: "3% weniger als im Basic-Paket. Gilt nur bei aktivierter Direktbuchung – Anfragen bleiben provisionsfrei." },
      { text: "Ranking-Bonus bei aktivierter Direktbuchung", isStrong: true, description: "Kurse mit aktivierter Direktbuchung erhalten zusätzlich einen Ranking-Vorteil gegenüber Kursen ohne Direktbuchung." },
      { text: "Keine Erfassungsservices inklusive", dim: true, excluded: true, separator: true, description: "Separat buchbar ab 75 CHF pro Kurs." },
      { text: "Medium Analytics", isStrong: true, description: "Performance-Daten und Teilnehmer-Insights." },
    ],
  },
  {
    id: "premium",
    title: "Premium",
    tagline: "Maximale Reichweite",
    priceText: "690 CHF",
    periodText: "/Jahr",
    accent: "purple",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Premium wählen",
    savingsNote: "5% weniger Kommission + 5 Erfassungsservices",

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 690,
    maxCourses: Infinity,
    maxPrioCourses: 15,
    maxCategoriesPerCourse: 3,
    commissionPct: 10,
    planFactor: 1.2,
    includedCaptureServices: 5,
    bookingFactorWithKursNavi: 1.2,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "15 Prio-Kurse", isStrong: true, description: "Sie wählen 15 Kurse als Prio-Kurse. Diese werden in Suche und Kategorieseiten prominent ganz oben angezeigt – noch vor Kursen ohne Priorisierung." },
      { text: "Erhöhtes Ranking für Prio-Kurse", isStrong: true, description: "Prio-Kurse erscheinen in allen relevanten Suchen und Kategorieübersichten weiter oben." },
      { text: "Bis 3 Kategorien pro Kurs", separator: true, description: "Pro Kurs können Sie bis zu 3 Kategorien wählen. So erscheint derselbe Kurs z.B. unter «Sport», «Fitness» und «Gesundheit» – und wird von deutlich mehr Interessenten gefunden." },
      { text: "10% Provision bei Direktbuchung", description: "5% weniger als im Basic-Paket. Gilt nur bei aktivierter Direktbuchung – Anfragen bleiben provisionsfrei." },
      { text: "Ranking-Bonus bei aktivierter Direktbuchung", isStrong: true, description: "Kurse mit aktivierter Direktbuchung erhalten zusätzlich einen Ranking-Vorteil gegenüber Kursen ohne Direktbuchung." },
      { text: "5 Erfassungsservices inklusive", isStrong: true, separator: true, description: "Wir erstellen professionelle Kursseiten für Sie." },
      { text: "Advanced Analytics", isStrong: true, description: "Vollständige Performance- und Marktdaten." },
    ],
  },
  {
    id: "enterprise",
    title: "Enterprise",
    tagline: "Für grosse Organisationen",
    priceText: "1'490 CHF",
    periodText: "/Jahr",
    accent: "orange",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Kontaktieren",
    savingsNote: "Tiefste Kommission + alle Kurse priorisiert",

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 1490,
    maxCourses: Infinity,
    maxPrioCourses: Infinity,
    maxCategoriesPerCourse: 5,
    commissionPct: 8,
    planFactor: 1.2,
    includedCaptureServices: 15,
    bookingFactorWithKursNavi: 1.2,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "Unbegrenzte Prio-Kurse", isStrong: true, description: "Alle Ihre Kurse können als Prio-Kurse gesetzt werden – ohne Limit. So erscheinen sämtliche Angebote ganz oben in Suche und Kategorien." },
      { text: "Erhöhtes Ranking für alle Kurse", isStrong: true, description: "Prio-Kurse erscheinen in allen relevanten Suchen und Kategorieübersichten weiter oben." },
      { text: "Bis 5 Kategorien pro Kurs", separator: true, description: "Pro Kurs bis zu 5 Kategorien – maximale Sichtbarkeit in Suche und Themenübersichten. Ein Kurs kann so z.B. unter «Sport», «Fitness», «Gesundheit», «Ernährung» und «Coaching» erscheinen." },
      { text: "8% Provision bei Direktbuchung", description: "Tiefste verfügbare Provision. Gilt nur bei aktivierter Direktbuchung – Anfragen bleiben provisionsfrei." },
      { text: "Ranking-Bonus bei aktivierter Direktbuchung", isStrong: true, description: "Kurse mit aktivierter Direktbuchung erhalten zusätzlich einen Ranking-Vorteil gegenüber Kursen ohne Direktbuchung." },
      { text: "15 Erfassungsservices inklusive", isStrong: true, separator: true, description: "Wir erstellen professionelle Kursseiten für Sie." },
      { text: "Advanced Analytics", isStrong: true, description: "Vollständige Performance- und Marktdaten." },
    ],
  },
];
