export const PLANS = [
  {
    id: "basic",
    title: "Basic",
    tagline: "Kostenloser Einstieg",
    priceText: "0 CHF",
    periodText: "/Jahr",
    accent: "green",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Basic wählen",
    savingsNote: null,

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 0,
    maxCourses: Infinity,
    maxPrioCourses: 0,
    maxCategoriesPerCourse: 1,
    commissionPct: 15,
    planFactor: 1.0,
    includedCaptureServices: 0,
    bookingFactorWithKursNavi: 1.3,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "Keine Prio-Kurse", dim: true, excluded: true, description: "Ab dem Pro-Paket verfügbar." },
      { text: "1 Kategorie pro Kurs", separator: true },
      { text: "15% Komm. bei Direktbuchung (inkl. Stripe)", description: "Anfrage-Kurse bleiben provisionsfrei." },
      { text: "Zusätzlicher Ranking-Bonus bei Direktbuchung", isStrong: true, description: "Kurse mit aktivierter Direktbuchung werden in der Suche höher gerankt." },
      { text: "Standard Listing", separator: true },
      { text: "Keine Erfassungsservices inklusive", dim: true, excluded: true, description: "Separat buchbar ab 75 CHF pro Kurs." },
      { text: "Basic Analytics", description: "Einfache Statistiken zu Aufrufen und Anfragen." },
    ],
  },
  {
    id: "pro",
    title: "Pro",
    tagline: "Für wachsende Anbieter",
    priceText: "290 CHF",
    periodText: "/Jahr",
    accent: "blue",
    badgeText: "BELIEBT",
    lift: true,
    buttonVariant: "solid",
    ctaLabel: "Pro wählen",
    savingsNote: "3% weniger Kommission als Basic",

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 290,
    maxCourses: Infinity,
    maxPrioCourses: 5,
    maxCategoriesPerCourse: 3,
    commissionPct: 12,
    planFactor: 1.2,
    includedCaptureServices: 0,
    bookingFactorWithKursNavi: 1.2,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "5 Prio-Kurse", isStrong: true },
      { text: "Erhöhtes Ranking für Prio-Kurse", isStrong: true, description: "Ihre Prio-Kurse erscheinen weiter oben in den Suchergebnissen." },
      { text: "Bis 3 Kategorien pro Kurs", separator: true, description: "Mehr Sichtbarkeit in verschiedenen Bereichen." },
      { text: "12% Komm. bei Direktbuchung", description: "3% weniger als im Basic-Paket." },
      { text: "Zusätzlicher Ranking-Bonus bei Direktbuchung", isStrong: true, description: "Kurse mit Direktbuchung erhalten automatisch einen Ranking-Vorteil." },
      { text: "Keine Erfassungsservices inklusive", dim: true, excluded: true, separator: true, description: "Separat buchbar ab 75 CHF pro Kurs." },
      { text: "Medium Analytics", isStrong: true, description: "Performance-Daten und Teilnehmer-Insights." },
    ],
  },
  {
    id: "premium",
    title: "Premium",
    tagline: "Maximale Reichweite",
    priceText: "690 CHF",
    periodText: "/Jahr",
    accent: "purple",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Premium wählen",
    savingsNote: "5% weniger Kommission + 5 Erfassungsservices",

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 690,
    maxCourses: Infinity,
    maxPrioCourses: 15,
    maxCategoriesPerCourse: 3,
    commissionPct: 10,
    planFactor: 1.2,
    includedCaptureServices: 5,
    bookingFactorWithKursNavi: 1.2,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "15 Prio-Kurse", isStrong: true },
      { text: "Erhöhtes Ranking für Prio-Kurse", isStrong: true, description: "Ihre Prio-Kurse erscheinen weiter oben in den Suchergebnissen." },
      { text: "Bis 3 Kategorien pro Kurs", separator: true, description: "Mehr Sichtbarkeit in verschiedenen Bereichen." },
      { text: "10% Komm. bei Direktbuchung", description: "5% weniger als im Basic-Paket." },
      { text: "Zusätzlicher Ranking-Bonus bei Direktbuchung", isStrong: true, description: "Kurse mit Direktbuchung erhalten automatisch einen Ranking-Vorteil." },
      { text: "5 Erfassungsservices inklusive", isStrong: true, separator: true, description: "Wir erstellen professionelle Kursseiten für Sie." },
      { text: "Advanced Analytics", isStrong: true, description: "Vollständige Performance- und Marktdaten." },
    ],
  },
  {
    id: "enterprise",
    title: "Enterprise",
    tagline: "Für grosse Organisationen",
    priceText: "1'490 CHF",
    periodText: "/Jahr",
    accent: "orange",
    badgeText: null,
    lift: false,
    buttonVariant: "outline",
    ctaLabel: "Kontaktieren",
    savingsNote: "Tiefste Kommission + alle Kurse priorisiert",

    // --- Machine-readable Paketlogik (v3.1) ---
    priceAnnualCHF: 1490,
    maxCourses: Infinity,
    maxPrioCourses: Infinity,
    maxCategoriesPerCourse: 5,
    commissionPct: 8,
    planFactor: 1.2,
    includedCaptureServices: 15,
    bookingFactorWithKursNavi: 1.2,
    bookingFactorWithoutKursNavi: 1.0,

    features: [
      { text: "Unbegrenzte Kurse" },
      { text: "Unbegrenzte Prio-Kurse", isStrong: true },
      { text: "Erhöhtes Ranking für Prio-Kurse", isStrong: true, description: "Alle Kurse erscheinen weiter oben in den Suchergebnissen." },
      { text: "Bis 5 Kategorien pro Kurs", separator: true, description: "Maximale Sichtbarkeit in verschiedenen Bereichen." },
      { text: "8% Komm. bei Direktbuchung", description: "Tiefste verfügbare Kommission." },
      { text: "Zusätzlicher Ranking-Bonus bei Direktbuchung", isStrong: true, description: "Kurse mit Direktbuchung erhalten automatisch einen Ranking-Vorteil." },
      { text: "15 Erfassungsservices inklusive", isStrong: true, separator: true, description: "Umfangreiches Onboarding-Paket inklusive." },
      { text: "Advanced Analytics", isStrong: true, description: "Vollständige Performance- und Marktdaten." },
    ],
  },
];
